### ISSUE TITLE
There a gap between the lines

### ISSUE THREAD

**Issue by woshiniming007** [graelo/pumas#23]
The tool is awesome.
Why is there a gap between the lines when I run this program, while there is none in your example image? I use the default terminal.app.

And a small suggestion: Can I use command 'sudo pumas' to start directly without add 'run' param? That would be more convenient.

<img width="687" alt="SCR-20240414-parv" src="https://github.com/graelo/pumas/assets/55045806/295fa030-97b2-485f-a346-4acd65802bc5">

**Comment by graelo** [comment]
Hello, thanks for the kind words, I truly appreciate. 

I imagine this is related to your current fonts. Would you consider trying with a font from https://www.nerdfonts.com? I think I got the horizontal bars from there. If this works and your font is not there you can use their resources to patch your own font (that's what I did). 

I hope this make sense. Tell me how it goes. 

Cheers

**Comment by graelo** [comment]
Anyway I should advertise clearly that requirement. Thanks for raising this issue.

**Comment by graelo** [comment]
Ok, with a little further investigation:

- The characters in question are Block Elements (U+2580..U+259F, see https://en.wikipedia.org/wiki/Block_Elements). These blocks are very likely already part of your font, no need for nerdfonts, sorry for the wrong suggestion.
- This issue seems to be a rendering issue in the Terminal.app. I could reproduce your issue by just running Pumas in the Terminal.app (see screenshot). I could eliminate the issue by reducing line spacing to about 0.75 instead of the default 1, but you may not like how your terminal looks when shrinked that much! 
- For the record, I'm sorry I did not test Pumas on the Terminal.app. I actually had forgotten about it after switching to  https://github.com/alacritty/alacritty on macOS and Linux a few years ago.
- I could add a flag to use different elements (like the tall bars in Alacritty), but it's going to use much more real estate on the screen and add complexity.
- Of course the workaround is to use Alacritty, but I understand this might be a lot to ask.

I'll give it some more thought. In the mean time I'm happy to hear about what you think.

**Comment by graelo** [comment]
Thanks.

Regarding the Swap, yes there's a catch. Let me explain.

On an OS, the Swap can grow and shrink, so contrary to all other metrics, the max available Swap value can evolve. If I had based the ratio of Swap on the current max (9.0 on your screenshot), but it had been larger previously (17.0 on your screenshot), then the Swap usage history would suddenly bump up to above 100%, due to the old values being likely between than 9.0 and 17.0. This would make the Swap history almost useless.

In order to let the user see the unsaturated history of Swap usage ratio, I specifically used the peak value for the computing the ratio, and let the bar graph be the instantaneous value. But, true, this leads to inconsistencies with the bar graph.

I don't know what's the best approach. I can at least document that in an FAQ section on the homepage, and I could add an option to let the history saturate.

**Comment by graelo** [comment]
I realize that my wording was sloppy, so my explanation above had 2 possible interpretations. Let me fix that.

For the swap, the horizontal bar displays the current Swap usage ratio: current swap size / current swap file size (7.3/9.0 ~ 82%), and the history graph displays the recent swap sizes (absolute values, not ratios); the y axis's range is between 0 and the peak value so far (17), meaning the history would have full vertical bars wherever the swap size was equal to the peak value. Because the peak value never decreases, the history graph can only ever display values up to the peak value, but never saturate.

Because none of the history graphs display any scalar value and they merely provide context, I don't think they can be misleading.

As a last resort, someone wanting access to all values can always stream the metrics using `pumas run --json`.

I hope this clarifies!

**Comment by graelo** [comment]
This has turned into a lengthy series of problems, leading you to now ask "Should _we_ prioritize...". I'm not fond of the direction this is taking.

Please create a new issue for each distinct topic.

However, I will address the concerns you've raised.

This tool operates within a terminal environment:
- If a terminal application struggles to display Block Elements correctly, the problem does not originate from this tool.
- The value of a Swap file changes over time; therefore, every tool must decide how to represent these values. My decision is justified, and unless a _better_ option is presented, I will maintain it.
- If the user chooses to reduce the terminal size, thus compelling the layout algorithm (from http://ratatui.rs/) to make decisions, the user must accept the outcomes of their choice. I will not enforce equal sizing for these two blocks (E and P-* clusters) because there is inherent complexity due to a) Ultra chips featuring several pairs of E and P-* clusters and b) my intention to introduce a vertical layout option. I view the issue of keeping sizes equal in limited space as a minor aesthetic concern. While I acknowledge your point, I am not prepared to allocate personal time to it.

Furthermore, the tool already supports a JSON streaming mode, enabling users to develop their applications as desired.
